version=11.0.17

image-oracle-jdk-11:
	docker build --platform linux/amd64 -t hurdes/ubuntu-oracle-jdk:${version} -f ./Dockerfile .

push-oracle-jdk-11:
	docker push hurdes/ubuntu-oracle-jdk:${version}